# FIVB Beach Leaderboard – dbt project
# Raw data lives in schema `raw`; staging and downstream in `staging` / `analytics`
name: 'fivb_leaderboard'
version: '1.0.0'
config-version: 2
profile: 'fivb_leaderboard'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  raw_schema: raw

models:
  fivb_leaderboard:
    staging:
      fivb:
        +schema: staging
        +materialized: view
        +docs:
          show: true
    core:
      fivb:
        +schema: core
        +materialized: view
        +docs:
          show: true
    mart:
      fivb:
        +schema: mart
        +materialized: view
        +docs:
          show: true
