name: "fivb_leaderboard"
version: "1.0.0"
config-version: 2

profile: "fivb_leaderboard"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fivb_leaderboard:
    +materialized: view

    staging:
      +schema: staging
      +tags: ["staging"]

    core:
      +schema: core
      +tags: ["core"]

    mart:
      +schema: mart
      +tags: ["mart"]
      +materialized: table

