# Marts: analytics-ready datasets
version: 2
models:
  - name: match_mart
    description: "One row per match with full tournament, round, team, player, ranking, and standings metadata."
    columns:
      - name: match_id
        description: "Unique match identifier (VIS No)."
        tests:
          - dbt_utils.at_least_one
      - name: tournament_id
      - name: played_at
      - name: tournament_name
      - name: season
      - name: tournament_gender
      - name: tournament_tier
      - name: tournament_start_date
      - name: tournament_end_date
      - name: tournament_city
      - name: tournament_country_code
      - name: tournament_country_name
      - name: tournament_season_year
      - name: tournament_is_major
      - name: round_name
      - name: round_bracket
      - name: round_phase
      - name: team1_display_name
      - name: team2_display_name
      - name: team1_ranking_position
      - name: team2_ranking_position
      - name: team1_finishing_pos
        description: "Team1's finishing position in this tournament (null if not in standings)."
      - name: team2_finishing_pos
        description: "Team2's finishing position in this tournament (null if not in standings)."
      - name: is_winner_team1
      - name: is_final
      - name: is_pool_phase
      - name: higher_seed_won

  - name: tournament_mart
    description: "One row per tournament + team with final ranking, tournament/team metadata, and sum of opponents' standings points that this team beat (performance beyond final position)."
    columns:
      - name: tournament_id
        description: "Unique tournament identifier (VIS No)."
        tests:
          - dbt_utils.at_least_one
      - name: team_id
        description: "Team identifier for this tournament."
      - name: tournament_name
      - name: season
      - name: season_year
      - name: tournament_tier
      - name: tournament_gender
      - name: tournament_start_date
      - name: tournament_end_date
      - name: tournament_duration_days
      - name: tournament_city
      - name: tournament_country_code
      - name: tournament_country_name
      - name: tournament_is_major
      - name: team_display_name
      - name: team_country_code
      - name: finishing_pos
        description: "Team's final position in this tournament (1 = champion)."
      - name: tournament_points
        description: "Points earned at this tournament (from standings)."
      - name: prize_money
      - name: entry_ranking_position
      - name: entry_ranking_points
      - name: is_podium
      - name: is_champion
      - name: sum_opponent_points_beaten
        description: "Sum of standings points of opponents this team beat (from GetBeachTournamentRanking Points). Null when points are missing from the API."
      - name: matches_played
        description: "Number of matches this team played in this tournament."
      - name: match_wins
        description: "Number of matches won."
      - name: match_losses
        description: "Number of matches lost (excludes matches with no winner)."
      - name: wins_vs_higher_seed
        description: "Wins against a team with a better (lower) world ranking at match time (upsets)."
      - name: losses_vs_lower_seed
        description: "Losses against a team with a worse (higher) world ranking at match time."
      - name: pool_wins
        description: "Wins in pool play."
      - name: elimination_wins
        description: "Wins in bracket/elimination play (non-pool)."
      - name: quality_win_loss_score
        description: "Tournament-wide scaled metric: beating a good team adds more, beating a bad team adds less; losing to a good team subtracts less, losing to a bad team subtracts more. Uses opponent finishing position (1=champion). Score is sum of per-match contributions; comparable across tournaments of same size."
      - name: quality_win_loss_score_points
        description: "Same logic as quality_win_loss_score but uses opponent entry_ranking_points (normalized by max in tournament). Beat high-points opponent = big +, lose to low-points = big -."

  - name: champion_mart
    description: "One row per tournament champion with full tournament, team, final match, and ranking-at-event context."
    columns:
      - name: tournament_id
        description: "Unique tournament identifier (VIS No)."
        tests:
          - dbt_utils.at_least_one
      - name: team_id
        description: "Champion team identifier for this tournament."
      - name: tournament_name
        description: "Official tournament name."
      - name: season
        description: "Season label (e.g. 2024)."
      - name: season_year
        description: "Numeric season year."
      - name: tournament_gender
        description: "Men / Women."
      - name: tournament_tier
        description: "Tournament tier (e.g. World Championship, Olympic Games)."
      - name: is_major
        description: "True for World Championship or Olympic Games."
      - name: tournament_start_date
        description: "Tournament start date."
      - name: tournament_end_date
        description: "Tournament end date."
      - name: tournament_duration_days
        description: "Length of tournament in days."
      - name: tournament_city
        description: "Host city."
      - name: tournament_host_country_code
        description: "Host country code."
      - name: tournament_host_country_name
        description: "Host country name."
      - name: tournament_status
        description: "Tournament status."
      - name: tournament_timezone
        description: "Tournament timezone."
      - name: champion_team_display_name
        description: "Champion team display name (Player A / Player B)."
      - name: champion_player_a_name
        description: "Champion player A full name."
      - name: champion_player_b_name
        description: "Champion player B full name."
      - name: champion_country_code
        description: "Champion team country code."
      - name: finishing_pos
        description: "Finishing position (1 for champion)."
      - name: points
        description: "Points earned at this tournament."
      - name: prize_money
        description: "Prize money for this placement."
      - name: final_played_at
        description: "When the final match was played."
      - name: final_opponent_display_name
        description: "Runner-up team display name."
      - name: final_opponent_country_code
        description: "Runner-up country code."
      - name: final_score_sets
        description: "Final match score (sets)."
      - name: final_duration_minutes
        description: "Final match duration in minutes."
      - name: final_round_name
        description: "Round name for the final (e.g. Final, Gold Medal Match)."
      - name: ranking_position_at_tournament
        description: "Champion team world ranking position at or just before tournament end."
      - name: ranking_type_at_tournament
        description: "Ranking type (e.g. World Tour) for the snapshot."
      - name: ranking_snapshot_date
        description: "Date of the ranking snapshot used."
      - name: is_top_10_at_tournament
        description: "True if ranking position was in top 10 at tournament time."
      - name: is_top_16_at_tournament
        description: "True if ranking position was in top 16 at tournament time (Olympic-relevant)."
